Manual build trigger button (#45) resolved
G-Node/gin-valid pull request #80
Opened 2022-06-24 07:41 UTC by cervenkam

Closes #45

The button is added directly to the template

2022-06-24 09:31 UTC, mpsonntag requested changes
Using the `/pubvalidate` route does not work with private repositories.

Further the public validation does not link the `latest` validation and therefore a triggered validation run would not show up on the results page which is what the issue tries to solve.

Most probably a new route is required that checks the permissions internally, runs the required validation and links the results appropriately.

2022-06-24 09:31 UTC, mpsonntag commented on internal/resources/templates/repolist.go
> +								<input type="submit" value="Validate once" />
Please change text to "Run validation"

2022-06-24 09:31 UTC, mpsonntag commented on internal/resources/templates/repolist.go
> +							<td class="name four wide"><form action="/pubvalidate" method="post">
Using the `/pubvalidate` route does not work with private repositories.

2022-06-29 07:06 UTC, cervenkam commented
This PR is closed for now due to the fact that private repositories are in this state _hard to validate_.

2022-06-29 07:06 UTC, closed without merging