User login and logout (#62, #69) resolved
G-Node/gin-valid pull request #95
Opened 2022-06-29 10:09 UTC by cervenkam

Closes #69, Closes #62

If the user logs in, the "Login" option is replaced with
his name. After user click on the string with his name,
he would logout.

2022-06-29 10:19 UTC, pavelsne approved these changes

2022-06-29 11:09 UTC, mpsonntag requested changes
Very nice PR, thanks!

2022-06-29 11:09 UTC, mpsonntag commented on internal/resources/templates/layout.go
> +									<a class="item" href="/logout">{{.UserName}}</a>
Please change it to "{{.UserName}} (logout)" to make it clear what happens when the link is used.

2022-06-30 08:36 UTC, mpsonntag approved these changes
Very nice test update, thank you!

2022-06-30 08:36 UTC, merged